def save_data():
 fileD = open("deliveries.txt", "a")
 fileD.write("Depot:\n")
 fileD.write("%s\n" % depot.get())
 fileD.write("Description:\n")
 fileD.write("%s\n" % description.get())
 fileD.write("Address:\n")
 fileD.write("%s\n" % address.get("1.0", END))
 depot.delete(0, END)
 description.delete(0, END)
 address.delete("1.0", END)