app = Tk()
app.title('Head-Ex Deliveries')
Label(app, text = "Depot:").pack()
#depot = Entry(app)
#depot.pack()
#Radiobutton(app, text = "Cambridge, MA").pack()
#Radiobutton(app, text = "Cambridge, UK").pack()
#Radiobutton(app, text = "Seattle, WA").pack()
Radiobutton(app, variable = depot, text = "Cambridge, MA", value = "Cambridge, MA").pack()
Radiobutton(app, variable = depot, text = "Cambridge, UK", value = "Cambridge, UK").pack()
Radiobutton(app, variable = depot, text = "Seattle, WA", value = "Seattle, WA").pack()
Label(app, text = "Description:").pack()
description = Entry(app)
description.pack()
Label(app, text = "Address:") .pack()
addres = Text (app)
address .pack()
Button(app, text = "Save", command = save_data).pack()
app.mainloop()